### ISSUE TITLE
Repository has no declared license

### ISSUE THREAD

**Issue by dannysauer** [fpytloun/docker-pulp#1]
It'd be ideal if this code had a license associated with it.  I'd prefer Apache, but any license which explicitly grants the ability to at least create non-commercial derivative works (in alignment with the expectation created by the GitHub "fork" button) would be useful. :)

**Comment by fpytloun** [comment]
Thank you for noticing :-) Added LICENSE file.

**Comment by dannysauer** [comment]
Thanks!  PR's opened to derived projects. :)
